### ISSUE TITLE
Problem using Redux with the modal

### ISSUE THREAD

**Issue by zakster12** [magicismight/react-native-root-modal#6]
Thank you for your library. It's very useful. I am having a problem when I try to use the connect method of React-redux like this:

```
import { connect } from 'react-redux';

class SignModal extends Component {
   ...
}

export default connect()(SignModal);
```

The SignModal is shown by Login Screen which is part of <StackNav />:

```
const App = () => (
    <Provider store={store}>
        <StackNav />
    </Provider>
);

AppRegistry.registerComponent('MyApp', () => App);
```

but I have the following error:

![screen shot 2017-05-10 at 8 39 47 am](https://cloud.githubusercontent.com/assets/25477229/25885418/dbc8c26a-3560-11e7-8f08-5754ab501d21.png)

Any clue why this is happening? I have this error only when I use the react-native-root-modal

**Comment by sckoh** [comment]
I have fork https://github.com/sckoh/react-native-root-modal
it will pass rootSiblings to your root App component.
then you can write like:

```
  render() {
    const { rootSiblings } = this.props;
    return (
      <Provider store={store}>
        <View
          style={{
            flex: 1,
            position: 'relative',
          }}
        >
          <App />
          {rootSiblings}
        </View>
      </Provider>
    );
  }
```

so that it will be in your <Provider> and you will be able to connect your modal component

**Comment by kid-wumeng** [comment]
same issue with MobX

**Comment by hellogerard** [comment]
@magicismight Thanks for the recent release. This is one of the most useful RN packages in my app because I have a lot of "dynamic" modals. Without root-modal, my other choices are using the native Modal which is not flexible enough, or creating my own hacky mechanism thru a root navigator component. I'd much rather use this package. 

But my modals are complicated enough to require Redux, which brings me to this issue. I think @sckoh's solution, or maybe another solution, supporting Redux should be a core feature of this package.

**Comment by magicismight** [comment]
Redux is supported on v3.0.0
